import './parts/lockscroll.js';
import './parts/mobmenu.js';
import './parts/moblang.js';
import './parts/modal.js';
import './parts/scrollto.js';
import './parts/accordion.js';
import './parts/banner.js';
import './parts/splidecust.js';
import './parts/splide.js';
